### PR TITLE
Indivo Localization

### PR DESCRIPTION
**Pull request by thiagogalesi**
Basic indivo localization UI task

To create the messages use:  ./manage.py makemessages -l (desired locale) -e .html,.ejs,.py

### CODE REVIEW

**Comment by thisisdhaas** [comment]
This looks great! A couple comments:
- The makemessages command doesn't run unless there is a top level `locale/` directory under `indivo_ui_server`: let's make sure we add that.
- Indivo won't be truly localized until we have some translation files. What locale are you using this for, and do you have an Indivo `*.po` file we can get into the repository?
- We should get some good documentation up to explain how localization works in Indivo. Are you interested in working on this?

**Comment by thisisdhaas** [comment]
Thanks Thiago! code is merged.

**Comment by thiagogalesi** [comment]
Thanks for merging, Daniel!

About the issues you raised, I'm working on pt-br locale, but it's not so
good right now. It will take some time to fix, I can send it at a later
time.

I think documentation should be mainly on the localization of the jmvc
templates and how it works, unfortunately, I don't have anything ready at
this time, and I'm a bit short on time right now

Thanks

Thiago

On Fri, Jun 17, 2011 at 12:43 PM, chbdhaas <
reply@reply.github.com>
wrote:

> Thanks Thiago! code is merged.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/chb/indivo_ui_server/pull/2#issuecomment-1388962

## 

## 

Thiago Galesi

**Comment by thisisdhaas** [comment]
Sounds good. Looking forward to seeing your translations when they are ready. I'll take a crack at documenting Indivo localization, and maybe when you get a bit more time you can add to it.

-Daniel

**Pull request merged**
